/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'crabinfer.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./crabinfer.android-arm64.node')
          } else {
            nativeBinding = require('@crabinfer/node-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'crabinfer.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./crabinfer.android-arm-eabi.node')
          } else {
            nativeBinding = require('@crabinfer/node-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'crabinfer.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crabinfer.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@crabinfer/node-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'crabinfer.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crabinfer.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@crabinfer/node-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'crabinfer.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crabinfer.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@crabinfer/node-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'crabinfer.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./crabinfer.darwin-universal.node')
      } else {
        nativeBinding = require('@crabinfer/node-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'crabinfer.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./crabinfer.darwin-x64.node')
          } else {
            nativeBinding = require('@crabinfer/node-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'crabinfer.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crabinfer.darwin-arm64.node')
          } else {
            nativeBinding = require('@crabinfer/node-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'crabinfer.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./crabinfer.freebsd-x64.node')
      } else {
        nativeBinding = require('@crabinfer/node-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'crabinfer.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crabinfer.linux-x64-musl.node')
            } else {
              nativeBinding = require('@crabinfer/node-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'crabinfer.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crabinfer.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@crabinfer/node-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'crabinfer.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crabinfer.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@crabinfer/node-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'crabinfer.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crabinfer.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@crabinfer/node-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'crabinfer.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crabinfer.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@crabinfer/node-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'crabinfer.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crabinfer.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@crabinfer/node-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'crabinfer.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crabinfer.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@crabinfer/node-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'crabinfer.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./crabinfer.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@crabinfer/node-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'crabinfer.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./crabinfer.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@crabinfer/node-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { MemoryPressure, ProviderTier, RoutingPolicy, RoutingReason, ModelCategory, DownloadStatus, version, detectDevice, estimateModelMemory, modelCatalog, modelsForDevice, recommendedModels, catalogEntry, peekModelMetadata, setCredential, getCredential, removeCredential, hasCredential, configuredProviders, validateCredential, CrabInferEngine, TokenStream, CrabInferProvider, CrabInferRouter, CrabInferVllm, ModelDownloadManager, SystemPrompt, ConversationMemory, MemoryStore, KnowledgeBase, parseToolCalls, hasToolCalls, extractTextFromResponse, ToolRegistry, McpServerRegistry } = nativeBinding

module.exports.MemoryPressure = MemoryPressure
module.exports.ProviderTier = ProviderTier
module.exports.RoutingPolicy = RoutingPolicy
module.exports.RoutingReason = RoutingReason
module.exports.ModelCategory = ModelCategory
module.exports.DownloadStatus = DownloadStatus
module.exports.version = version
module.exports.detectDevice = detectDevice
module.exports.estimateModelMemory = estimateModelMemory
module.exports.modelCatalog = modelCatalog
module.exports.modelsForDevice = modelsForDevice
module.exports.recommendedModels = recommendedModels
module.exports.catalogEntry = catalogEntry
module.exports.peekModelMetadata = peekModelMetadata
module.exports.setCredential = setCredential
module.exports.getCredential = getCredential
module.exports.removeCredential = removeCredential
module.exports.hasCredential = hasCredential
module.exports.configuredProviders = configuredProviders
module.exports.validateCredential = validateCredential
module.exports.CrabInferEngine = CrabInferEngine
module.exports.TokenStream = TokenStream
module.exports.CrabInferProvider = CrabInferProvider
module.exports.CrabInferRouter = CrabInferRouter
module.exports.CrabInferVllm = CrabInferVllm
module.exports.ModelDownloadManager = ModelDownloadManager
module.exports.SystemPrompt = SystemPrompt
module.exports.ConversationMemory = ConversationMemory
module.exports.MemoryStore = MemoryStore
module.exports.KnowledgeBase = KnowledgeBase
module.exports.parseToolCalls = parseToolCalls
module.exports.hasToolCalls = hasToolCalls
module.exports.extractTextFromResponse = extractTextFromResponse
module.exports.ToolRegistry = ToolRegistry
module.exports.McpServerRegistry = McpServerRegistry
