/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Memory pressure levels. */
export const enum MemoryPressure {
  Normal = 'Normal',
  Warning = 'Warning',
  Critical = 'Critical',
  Terminal = 'Terminal'
}
/** Provider infrastructure tier. */
export const enum ProviderTier {
  Local = 'Local',
  SelfHosted = 'SelfHosted',
  Cloud = 'Cloud'
}
/** Routing policy. */
export const enum RoutingPolicy {
  LocalFirst = 'LocalFirst',
  CloudFirst = 'CloudFirst',
  LocalOnly = 'LocalOnly',
  Auto = 'Auto',
  SelfHostedFirst = 'SelfHostedFirst'
}
/** Routing reason — why a provider was selected. */
export const enum RoutingReason {
  LocalAvailable = 'LocalAvailable',
  MemoryPressureFallback = 'MemoryPressureFallback',
  NoLocalModel = 'NoLocalModel',
  CloudPreferred = 'CloudPreferred',
  NetworkUnavailable = 'NetworkUnavailable',
  PrivacyMode = 'PrivacyMode',
  FallbackAfterError = 'FallbackAfterError',
  SelfHostedAvailable = 'SelfHostedAvailable',
  SelfHostedPreferred = 'SelfHostedPreferred',
  DataSovereignty = 'DataSovereignty'
}
/** Model use-case category. */
export const enum ModelCategory {
  General = 'General',
  Code = 'Code',
  Reasoning = 'Reasoning'
}
/** Download status. */
export const enum DownloadStatus {
  NotDownloaded = 'NotDownloaded',
  Downloading = 'Downloading',
  Downloaded = 'Downloaded',
  Failed = 'Failed'
}
/** Device capabilities information. */
export interface DeviceInfo {
  deviceModel: string
  totalMemoryBytes: number
  availableMemoryBytes: number
  hasMetalGpu: boolean
  hasNeuralEngine: boolean
  recommendedQuant: string
  maxModelSizeB: number
  maxModelFileSizeBytes: number
  chipName: string
  chipVariant: string
  recommendedContextLength: number
}
/** Engine configuration. */
export interface EngineConfig {
  modelPath: string
  maxTokens: number
  temperature: number
  topP: number
  contextLength: number
  useMetal: boolean
  memoryLimitBytes: number
  metallibPath: string
}
/** Generated token output. */
export interface TokenOutput {
  text: string
  tokenId: number
  probability: number
  isEndOfSequence: boolean
}
/** Generation statistics. */
export interface GenerationStats {
  tokensGenerated: number
  tokensPerSecond: number
  timeToFirstTokenMs: number
  totalTimeMs: number
  peakMemoryBytes: number
  computeBackend: string
}
/** Model metadata. */
export interface ModelInfo {
  modelName: string
  architecture: string
  parameterCount: number
  quantization: string
  fileSizeBytes: number
  contextLength: number
  vocabSize: number
  isMoe: boolean
  expertCount: number
  expertUsedCount: number
  activeParameterCount: number
}
/** A chat message in a conversation. */
export interface ChatMessage {
  role: string
  content: string
}
/** Unified completion request. */
export interface CompletionRequest {
  model?: string
  messages: Array<ChatMessage>
  maxTokens: number
  temperature?: number
  topP?: number
  systemPrompt?: string
  apiKeyOverride?: string
}
/** Unified completion response. */
export interface CompletionResponse {
  content: string
  model: string
  providerName: string
  stopReason: string
  inputTokens: number
  outputTokens: number
  routingInfo: string
}
/** Describes a model available from a provider. */
export interface ModelDescriptor {
  id: string
  name: string
  provider: string
  isLocal: boolean
  contextLength: number
}
/** Provider configuration. */
export interface ProviderConfig {
  providerType: string
  apiKey?: string
  baseUrl?: string
  defaultModel?: string
  timeoutSeconds?: number
  tierOverride?: string
}
/** Router configuration. */
export interface RouterConfig {
  policy: RoutingPolicy
  privacyMode?: boolean
  ollamaIsLocal?: boolean
  dataSovereignty?: boolean
}
/** Routing decision details. */
export interface RoutingDecision {
  providerName: string
  reason: RoutingReason
  providersTried: number
  isLocal: boolean
  providerTier: ProviderTier
  memoryPressure: MemoryPressure
  networkAvailable: boolean
  latencyMs: number
}
/** A model in the curated catalog. */
export interface CatalogEntry {
  id: string
  name: string
  hfRepo: string
  ggufFile: string
  tokenizerRepo: string
  sizeBytes: number
  paramCountB: number
  activeParamCountB: number
  quant: string
  architecture: string
  minRamGb: number
  category: ModelCategory
  isMoe: boolean
  sha256: string
  requiresAuth: boolean
}
/** vLLM server metrics. */
export interface VllmServerMetrics {
  gpuCacheUsage: number
  requestsRunning: number
  requestsWaiting: number
  requestsSwapped: number
}
/** vLLM-specific completion options. */
export interface VllmCompletionOptions {
  repetitionPenalty?: number
  minP?: number
  guidedJson?: string
  guidedRegex?: string
}
/** A successfully downloaded model with local paths. */
export interface DownloadedModel {
  id: string
  modelPath: string
  tokenizerPath: string
  sizeBytes: number
  downloadedAt: string
}
/** Get the CrabInfer version. */
export declare function version(): string
/** Detect the current device's capabilities. */
export declare function detectDevice(): DeviceInfo
/**
 * Estimate peak memory usage for a GGUF model before loading.
 * Returns estimated bytes as i64 (safe for JS number up to 2^53).
 */
export declare function estimateModelMemory(modelPath: string, contextLength: number): number
/** Return the full curated model catalog. */
export declare function modelCatalog(): Array<CatalogEntry>
/** Return catalog models that fit on the current device. */
export declare function modelsForDevice(device: DeviceInfo): Array<CatalogEntry>
/** Return recommended models for the current device. */
export declare function recommendedModels(device: DeviceInfo): Array<CatalogEntry>
/** Look up a single catalog entry by ID. */
export declare function catalogEntry(id: string): CatalogEntry | null
/**
 * Peek at GGUF model metadata without loading weights.
 * Returns architecture, parameter count, quantization, etc. from the file header only.
 */
export declare function peekModelMetadata(modelPath: string, contextLength: number): ModelInfo
/** Store an API key for a cloud provider. */
export declare function setCredential(provider: string, apiKey: string): void
/** Retrieve the stored API key for a provider. */
export declare function getCredential(provider: string): string | null
/** Remove a stored API key. */
export declare function removeCredential(provider: string): void
/** Check if a key is stored for the given provider. */
export declare function hasCredential(provider: string): boolean
/** List provider names that have stored keys. */
export declare function configuredProviders(): Array<string>
/** Validate a stored API key by making a lightweight API call. */
export declare function validateCredential(provider: string): boolean
/** A chat message (role + content) for JS. */
export interface JsChatMessage {
  role: string
  content: string
}
/** A search result from the knowledge base. */
export interface JsSearchResult {
  text: string
  source: string
  score: number
  chunkIndex: number
}
/** A parsed tool call from model output. */
export interface JsToolCall {
  name: string
  arguments: string
}
/** Result of executing a tool. */
export interface JsToolResult {
  toolName: string
  output: string
  isError: boolean
}
/** Record of a tool execution during an agent turn. */
export interface JsAgentToolExecution {
  toolName: string
  arguments: string
  output: string
  isError: boolean
}
/** Agent response from a single turn. */
export interface JsAgentResponse {
  text: string
  toolCalls: Array<JsAgentToolExecution>
  rounds: number
}
/**
 * Parse tool calls from model output text.
 *
 * Looks for `<tool_call>{"name": "...", "arguments": {...}}</tool_call>` patterns.
 */
export declare function parseToolCalls(text: string): Array<JsToolCall>
/** Check if text contains tool calls. */
export declare function hasToolCalls(text: string): boolean
/** Extract plain text from a response (removing tool_call blocks). */
export declare function extractTextFromResponse(text: string): string
/** MCP server configuration for JS. */
export interface JsMcpServerConfig {
  name: string
  /** "stdio" or "http" */
  transport: string
  /** Command (stdio) or URL (http) */
  command: string
  args: Array<string>
  enabled: boolean
  description: string
}
/** MCP tool info for JS. */
export interface JsMcpToolInfo {
  name: string
  description: string
  inputSchema: string
}
/** Local inference engine — loads GGUF models and runs on-device inference. */
export declare class CrabInferEngine {
  /** Create a new engine with the given configuration. */
  constructor(config: EngineConfig)
  /** Load a GGUF model file (async — runs on libuv thread pool). */
  loadModel(modelPath: string): Promise<void>
  /** Get loaded model info (sync — fast). */
  modelInfo(): ModelInfo
  /** Generate a complete response (async — runs on libuv thread pool). */
  complete(prompt: string, maxTokens: number, temperature?: number | undefined | null): Promise<string>
  /** Get the next token (sync — used for manual streaming loops). */
  nextToken(prompt: string): TokenOutput | null
  /** Reset the engine state. */
  reset(): void
  /** Get generation stats from the last complete() call. */
  lastStats(): GenerationStats | null
  /** Get current memory pressure level (sync — fast). */
  memoryPressure(): MemoryPressure
  /** Reduce memory usage by clearing caches. */
  reduceMemory(): void
  /** Unload the current model. */
  unloadModel(): void
  /** Check if a model is currently loaded. */
  isModelLoaded(): boolean
  /** Get current Metal GPU memory allocation in bytes. */
  metalAllocatedBytes(): number
  /**
   * Register a callback for memory pressure changes.
   * The callback receives (oldLevel: string, newLevel: string).
   */
  onMemoryPressure(callback: (oldLevel: string, newLevel: string) => void): void
  /** Run a load/unload stress test (async — long running). */
  stressTest(modelPath: string, cycles: number, tokensPerCycle: number): Promise<string[]>
}
/**
 * Streaming token iterator. Call `next()` to get the next token as a Promise.
 * Implements the async iterator protocol via `index.js` patching.
 */
export declare class TokenStream {
  /**
   * Get the next token. Returns `Promise<TokenOutput | null>`.
   * Returns `null` when the stream is exhausted.
   */
  next(): Promise<TokenOutput | null>
}
/** Unified provider interface for local and cloud LLM inference. */
export declare class CrabInferProvider {
  /** Create a cloud provider from configuration. */
  static create(config: ProviderConfig): CrabInferProvider
  /** Create a local inference provider. */
  static createLocal(engineConfig: EngineConfig): CrabInferProvider
  /** Provider name ("local", "openai", "anthropic", etc.). */
  name(): string
  /** Generate a complete response. */
  complete(request: CompletionRequest): CompletionResponse
  /** Start streaming and return a TokenStream (async iterator). */
  stream(request: CompletionRequest): TokenStream
  /** List models available from this provider. */
  availableModels(): Array<ModelDescriptor>
  /** Check if the provider is reachable/configured. */
  isAvailable(): boolean
}
/** Smart router that automatically selects between local, self-hosted, and cloud providers. */
export declare class CrabInferRouter {
  /** Create a router with optional local and cloud providers. */
  constructor(config: RouterConfig, localConfig: EngineConfig | undefined | null, cloudConfigs: Array<ProviderConfig>)
  /** Router name. */
  name(): string
  /** Generate a complete response, routing automatically. */
  complete(request: CompletionRequest): CompletionResponse
  /** Start streaming, routing automatically. Returns a TokenStream. */
  stream(request: CompletionRequest): TokenStream
  /** List models available from all configured providers. */
  availableModels(): Array<ModelDescriptor>
  /** Check if any provider is available. */
  isAvailable(): boolean
  /** Set network availability (call when connectivity changes). */
  setNetworkAvailable(available: boolean): void
  /** Get the routing decision from the last complete() or stream() call. */
  lastRoutingDecision(): RoutingDecision | null
}
/** vLLM provider with health checks, Prometheus metrics, and guided decoding. */
export declare class CrabInferVllm {
  /** Create a vLLM provider. */
  constructor(config: ProviderConfig)
  /** Provider name: "vllm". */
  name(): string
  /** Generate a complete response. */
  complete(request: CompletionRequest): CompletionResponse
  /** Generate a complete response with vLLM-specific options. */
  completeWithOptions(request: CompletionRequest, options: VllmCompletionOptions): CompletionResponse
  /** Start streaming and return a TokenStream. */
  stream(request: CompletionRequest): TokenStream
  /** List models served by the vLLM instance. */
  availableModels(): Array<ModelDescriptor>
  /** Check if the vLLM server is reachable. */
  isAvailable(): boolean
  /** Check vLLM server health via GET /health. */
  health(): boolean
  /** Scrape Prometheus metrics from the vLLM server. */
  serverMetrics(): VllmServerMetrics
}
/** Manages model downloads from HuggingFace with resume and integrity checks. */
export declare class ModelDownloadManager {
  /** Create a download manager with the default storage directory. */
  constructor()
  /** Create a download manager with a custom storage directory. */
  static withDirectory(directory: string): ModelDownloadManager
  /** Download a model (async with optional progress callback). */
  download(entry: CatalogEntry, onProgress?: (bytesDownloaded: number, bytesTotal: number, phase: string) => void): Promise<DownloadedModel>
  /** Check if a model is downloaded by catalog ID. */
  isDownloaded(catalogId: string): boolean
  /** Get the model file path for a downloaded model. */
  modelPath(catalogId: string): string | null
  /** Get the tokenizer path for a downloaded model. */
  tokenizerPath(catalogId: string): string | null
  /** List all downloaded models. */
  listDownloaded(): Array<DownloadedModel>
  /** Delete a downloaded model by catalog ID. */
  delete(catalogId: string): void
  /** Total disk usage of all downloaded models in bytes. */
  totalDiskUsage(): number
  /** Get the storage directory path. */
  storageDirectory(): string
}
/** Composable system prompt builder. */
export declare class SystemPrompt {
  /** Create an empty system prompt. */
  constructor()
  /** Set the identity section. */
  identity(identity: string): this
  /** Add an instruction. */
  instruction(instruction: string): this
  /** Set the output format. */
  outputFormat(format: string): this
  /** Set the token budget. */
  tokenBudget(budget: number): this
  /** Render the system prompt. */
  build(): string
  /** Render with injected facts and knowledge context. */
  buildWithContext(facts: Array<string>, knowledgeChunks: Array<string>): string
  /** Estimate token count. */
  estimateTokens(): number
  /** Save to JSON string. */
  toJson(): string
  /** Load from JSON string. */
  static fromJson(json: string): SystemPrompt
  /** Template: coding assistant. */
  static codingAssistant(): SystemPrompt
  /** Template: document Q&A. */
  static documentQa(): SystemPrompt
  /** Template: conversational. */
  static conversational(): SystemPrompt
}
/** Conversation memory for multi-turn chat history. */
export declare class ConversationMemory {
  /** Create a new conversation with the given ID. */
  constructor(id: string)
  /** Set the maximum number of messages. */
  withMaxMessages(max: number): void
  /** Set the token budget. */
  withTokenBudget(budget: number): void
  /** Set the file path for persistence. */
  withPersistPath(path: string): void
  /** Get the conversation ID. */
  get id(): string
  /** Add a user message. */
  addUserMessage(content: string): void
  /** Add an assistant message. */
  addAssistantMessage(content: string): void
  /** Add a message with a specific role. */
  addMessage(role: string, content: string): void
  /** Get all messages as an array of {role, content}. */
  messages(): Array<JsChatMessage>
  /** Get the N most recent messages. */
  recentMessages(count: number): Array<JsChatMessage>
  /** Get the number of messages. */
  get messageCount(): number
  /** Estimate total token count. */
  estimateTokens(): number
  /** Clear all messages. */
  clear(): void
  /** Set a summary of older messages. */
  setSummary(summary: string): void
  /** Save to disk. */
  save(): void
  /** Load from a JSON file. */
  static load(path: string): ConversationMemory
}
/** Persistent store for user/context facts. */
export declare class MemoryStore {
  /** Create a new empty store. */
  constructor()
  /** Set the file path for persistence. */
  withPersistPath(path: string): void
  /** Add or update a fact. */
  addFact(key: string, value: string): void
  /** Remove a fact. Returns true if it existed. */
  removeFact(key: string): boolean
  /** Get the value of a fact. */
  getValue(key: string): string | null
  /** Check if a fact exists. */
  hasFact(key: string): boolean
  /** Get the number of facts. */
  get count(): number
  /** Get all facts as strings for prompt injection. */
  asPromptContext(): Array<string>
  /** Clear all facts. */
  clear(): void
  /** Save to disk. */
  save(): void
  /** Load from a JSON file. */
  static load(path: string): MemoryStore
}
/** RAG knowledge base — add documents, query for relevant context. */
export declare class KnowledgeBase {
  /** Create a knowledge base with TF-IDF embeddings (offline, no API key needed). */
  constructor()
  /** Create a knowledge base with OpenAI embeddings. */
  static withOpenai(apiKey: string): KnowledgeBase
  /** Set the file path for persisting the vector store. */
  setPersistPath(path: string): void
  /**
   * Add a text document to the knowledge base.
   * Returns the number of chunks created.
   */
  addText(source: string, text: string): number
  /**
   * Add a file to the knowledge base.
   * Returns the number of chunks created.
   */
  addFile(path: string): number
  /** Remove a document and all its chunks. */
  removeDocument(source: string): void
  /** Query for relevant chunks. */
  query(text: string, topK: number): Array<JsSearchResult>
  /** Query and return only text strings (for prompt injection). */
  queryForPrompt(text: string, topK: number): Array<string>
  /** Get the number of indexed documents. */
  get documentCount(): number
  /** Get the number of stored chunks. */
  get chunkCount(): number
  /** List all indexed document sources. */
  documentSources(): Array<string>
  /** Get the embedding provider name. */
  get embedderName(): string
  /** Save the vector store to disk. */
  save(): void
  /** Clear all documents. */
  clear(): void
}
/** Registry of tools that can be used by the agent. */
export declare class ToolRegistry {
  /** Create a tool registry with all built-in tools (file_read, file_write, file_list, shell_exec, web_fetch). */
  constructor()
  /** Get all registered tool names. */
  toolNames(): Array<string>
  /** Generate the tools section for a system prompt. */
  toolsPrompt(): string
  /** Number of registered tools. */
  get count(): number
  /** Execute a tool call by name with JSON arguments. */
  execute(name: string, argumentsJson: string): JsToolResult
  /**
   * Connect to an MCP stdio server and register its tools.
   * Returns the number of tools registered.
   */
  connectMcpStdio(command: string, args: Array<string>): number
  /**
   * Connect to an MCP HTTP server and register its tools.
   * Returns the number of tools registered.
   */
  connectMcpHttp(url: string): number
}
/** Registry of configured MCP servers. */
export declare class McpServerRegistry {
  /** Create an empty registry. */
  constructor()
  /** Load from a file path. */
  static load(path: string): McpServerRegistry
  /** Load from the default location (~/.crabinfer/mcp-servers.json). */
  static loadDefault(): McpServerRegistry
  /** Save to disk. */
  save(): void
  /** Set the file path for persistence. */
  withPersistPath(path: string): void
  /** Add a server configuration. */
  add(config: JsMcpServerConfig): void
  /** Remove a server by name. */
  remove(name: string): boolean
  /** Enable or disable a server. */
  setEnabled(name: string, enabled: boolean): boolean
  /** Get all server configs. */
  servers(): Array<JsMcpServerConfig>
  /** Number of configured servers. */
  get count(): number
}
