//! Continuous batching engine loop.
//!
//! The engine loop runs in a dedicated thread, repeatedly:
//! 1. Draining new requests from the submission channel
//! 2. Running the scheduler to decide what to compute
//! 3. Building batched inputs and running the model forward pass
//! 4. Sampling output tokens and sending them to clients
//! 5. Checking stop conditions and cleaning up finished sequences
//!
//! The async HTTP handlers communicate with the engine loop through:
//! - `std::sync::mpsc` channel for submitting requests (non-blocking send)
//! - `tokio::sync::mpsc` per-request channels for receiving generated tokens

use std::collections::HashMap;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::Arc;

use candle_core::{DType, Device, Result as CandleResult, Tensor};
use tokenizers::Tokenizer;

use super::kernels::BLOCK_SIZE;
use super::kv_cache::KVCacheConfig;
use super::models::{ForwardContext, ModelRunner};
use super::scheduler::{Scheduler, SchedulerConfig, SchedulerOutput};
use super::sequence::{FinishReason, SamplingParams, SeqId};
use super::speculative::{self, SpeculativeState};

// ─── Public types ────────────────────────────────────────────────────────

/// Token generated by the serving engine, sent to clients via channel.
#[derive(Debug, Clone)]
pub struct GeneratedToken {
    /// The generated token ID.
    pub token_id: u32,
    /// If set, generation is complete and this is the reason.
    pub finish_reason: Option<FinishReason>,
}

/// Configuration for the serving engine.
#[derive(Debug, Clone)]
pub struct ServingEngineConfig {
    /// Maximum concurrent sequences.
    pub max_num_seqs: usize,
    /// Maximum tokens per scheduling step.
    pub max_num_batched_tokens: usize,
    /// Number of KV cache blocks to allocate.
    pub num_kv_cache_blocks: usize,
    /// Enable prefix caching.
    pub enable_prefix_cache: bool,
}

impl Default for ServingEngineConfig {
    fn default() -> Self {
        Self {
            max_num_seqs: 64,
            max_num_batched_tokens: 2048,
            num_kv_cache_blocks: 256,
            enable_prefix_cache: true,
        }
    }
}

/// Errors from the serving engine.
#[derive(Debug)]
pub enum EngineError {
    /// The engine has shut down.
    Shutdown,
    /// Too many concurrent requests (queue full).
    Overloaded,
}

impl std::fmt::Display for EngineError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            EngineError::Shutdown => write!(f, "engine has shut down"),
            EngineError::Overloaded => write!(f, "server is overloaded, try again later"),
        }
    }
}

impl std::error::Error for EngineError {}

// ─── Engine handle ───────────────────────────────────────────────────────

/// Handle for submitting requests to the engine loop.
///
/// The engine loop runs in a dedicated background thread. Requests are
/// submitted via channel and tokens are received via per-request channels.
///
/// `EngineHandle` is `Clone + Send + Sync` — share it across async tasks
/// by cloning or wrapping in `Arc`.
pub struct EngineHandle {
    request_tx: std::sync::mpsc::Sender<EngineRequest>,
    tokenizer: Arc<Tokenizer>,
    eos_token_id: u32,
    shutdown: Arc<AtomicBool>,
    /// Number of in-flight requests (for queue depth / load shedding).
    in_flight: Arc<std::sync::atomic::AtomicUsize>,
    /// Maximum concurrent requests before rejecting with 429.
    max_in_flight: usize,
}

impl Clone for EngineHandle {
    fn clone(&self) -> Self {
        Self {
            request_tx: self.request_tx.clone(),
            tokenizer: self.tokenizer.clone(),
            eos_token_id: self.eos_token_id,
            shutdown: self.shutdown.clone(),
            in_flight: self.in_flight.clone(),
            max_in_flight: self.max_in_flight,
        }
    }
}

impl EngineHandle {
    /// Start the serving engine with the given model and configuration.
    ///
    /// Allocates KV cache memory, creates the scheduler, and spawns a
    /// background thread running the continuous batching loop.
    pub fn start(
        model: Box<dyn ModelRunner>,
        tokenizer: Tokenizer,
        eos_token_id: u32,
        device: Device,
        config: ServingEngineConfig,
    ) -> CandleResult<Self> {
        Self::start_inner(model, tokenizer, eos_token_id, device, config, None)
    }

    /// Start the serving engine with speculative decoding (draft model).
    pub fn start_with_draft(
        model: Box<dyn ModelRunner>,
        tokenizer: Tokenizer,
        eos_token_id: u32,
        device: Device,
        config: ServingEngineConfig,
        speculative: SpeculativeState,
    ) -> CandleResult<Self> {
        Self::start_inner(
            model,
            tokenizer,
            eos_token_id,
            device,
            config,
            Some(speculative),
        )
    }

    fn start_inner(
        model: Box<dyn ModelRunner>,
        tokenizer: Tokenizer,
        eos_token_id: u32,
        device: Device,
        config: ServingEngineConfig,
        speculative: Option<SpeculativeState>,
    ) -> CandleResult<Self> {
        let model_config = model.config().clone();

        // KV cache dtype: use F32 to match model compute dtype.
        // TODO: add F32→F16 conversion in reshape_and_cache for memory efficiency
        let kv_dtype = DType::F32;

        // Allocate KV cache tensors
        let kv_caches = allocate_kv_caches(
            model_config.num_layers,
            config.num_kv_cache_blocks,
            model_config.num_kv_heads,
            model_config.head_size,
            kv_dtype,
            &device,
        )?;

        tracing::info!(
            "Allocated {} KV cache blocks ({} tokens capacity, {} layers)",
            config.num_kv_cache_blocks,
            config.num_kv_cache_blocks * BLOCK_SIZE,
            model_config.num_layers,
        );

        // Create scheduler
        let kv_cache_config = KVCacheConfig {
            block_size: BLOCK_SIZE,
            num_blocks: config.num_kv_cache_blocks,
            num_kv_heads: model_config.num_kv_heads,
            head_size: model_config.head_size,
            num_layers: model_config.num_layers,
            enable_prefix_cache: config.enable_prefix_cache,
        };
        let scheduler_config = SchedulerConfig {
            max_num_batched_tokens: config.max_num_batched_tokens,
            max_num_seqs: config.max_num_seqs,
            kv_cache: kv_cache_config,
        };
        let scheduler = Scheduler::new(scheduler_config);

        // Create channels and shutdown signal
        let (request_tx, request_rx) = std::sync::mpsc::channel();
        let shutdown = Arc::new(AtomicBool::new(false));

        if speculative.is_some() {
            tracing::info!("Speculative decoding enabled");
        }

        // Spawn engine loop in a dedicated thread
        let mut engine = ServingEngineInner {
            scheduler,
            model,
            kv_caches,
            device,
            eos_token_id,
            token_senders: HashMap::new(),
            request_rx,
            shutdown: shutdown.clone(),
            speculative,
        };

        std::thread::Builder::new()
            .name("crabinfer-engine".into())
            .spawn(move || engine.run())
            .map_err(|e| {
                candle_core::Error::Msg(format!("failed to spawn engine thread: {e}"))
            })?;

        Ok(Self {
            request_tx,
            tokenizer: Arc::new(tokenizer),
            eos_token_id,
            shutdown,
            in_flight: Arc::new(std::sync::atomic::AtomicUsize::new(0)),
            max_in_flight: config.max_num_seqs,
        })
    }

    /// Submit an inference request.
    ///
    /// Returns a receiver that yields generated tokens. When the receiver
    /// is dropped (e.g., client disconnects), the engine automatically
    /// cancels the request on the next scheduling step.
    pub fn submit(
        &self,
        prompt_tokens: Vec<u32>,
        sampling_params: SamplingParams,
    ) -> Result<tokio::sync::mpsc::Receiver<GeneratedToken>, EngineError> {
        // Check queue depth — reject early if overloaded
        let current = self.in_flight.load(Ordering::Relaxed);
        if current >= self.max_in_flight {
            return Err(EngineError::Overloaded);
        }
        self.in_flight.fetch_add(1, Ordering::Relaxed);

        let in_flight = self.in_flight.clone();
        let (tx, rx) = tokio::sync::mpsc::channel(32);
        let request = EngineRequest {
            prompt_tokens,
            sampling_params,
            token_sender: tx,
            in_flight_counter: Some(in_flight),
        };
        self.request_tx
            .send(request)
            .map_err(|_| EngineError::Shutdown)?;
        Ok(rx)
    }

    /// Number of in-flight requests (for metrics/health checks).
    pub fn in_flight_count(&self) -> usize {
        self.in_flight.load(Ordering::Relaxed)
    }

    /// Get a reference to the shared tokenizer.
    pub fn tokenizer(&self) -> &Tokenizer {
        &self.tokenizer
    }

    /// Get the EOS token ID.
    pub fn eos_token_id(&self) -> u32 {
        self.eos_token_id
    }

    /// Encode a text string into token IDs.
    pub fn encode(&self, text: &str) -> Result<Vec<u32>, EngineError> {
        let encoding = self
            .tokenizer
            .encode(text, false)
            .map_err(|_| EngineError::Shutdown)?;
        Ok(encoding.get_ids().to_vec())
    }

    /// Decode token IDs into a text string.
    pub fn decode(&self, token_ids: &[u32]) -> Result<String, EngineError> {
        self.tokenizer
            .decode(token_ids, true)
            .map_err(|_| EngineError::Shutdown)
    }

    /// Signal the engine loop to shut down gracefully.
    pub fn shutdown(&self) {
        self.shutdown.store(true, Ordering::Release);
    }
}

// ─── Internal types ──────────────────────────────────────────────────────

/// A request submitted to the engine loop via channel.
struct EngineRequest {
    prompt_tokens: Vec<u32>,
    sampling_params: SamplingParams,
    token_sender: tokio::sync::mpsc::Sender<GeneratedToken>,
    /// Shared counter to decrement when this request completes.
    in_flight_counter: Option<Arc<std::sync::atomic::AtomicUsize>>,
}

/// Batched input tensors for a single forward pass.
struct BatchInput {
    /// Token IDs for all sequences concatenated. `[total_tokens]` u32.
    input_ids: Tensor,
    /// Per-token positions. `[total_tokens]` u32.
    positions: Tensor,
    /// Slot mapping for KV cache writes. `[total_tokens]` u32.
    slot_mapping: Tensor,
    /// Block table. `[num_seqs, max_blocks_per_seq]` u32.
    block_table: Tensor,
    /// Context length per sequence. `[num_seqs]` u32.
    context_lens: Tensor,
    /// CSR offsets into the flat token tensor. Length = num_seqs + 1.
    query_start_loc: Vec<usize>,
    /// Total context length per sequence.
    seq_lens: Vec<usize>,
    /// Maximum context length across all sequences.
    max_context_len: usize,
    /// Whether all sequences are in decode mode (1 token each).
    is_all_decode: bool,
}

impl BatchInput {
    /// Create a `ForwardContext` referencing this batch's tensors.
    fn forward_context<'a>(
        &'a self,
        kv_caches: &'a [(Tensor, Tensor)],
    ) -> ForwardContext<'a> {
        ForwardContext {
            positions: &self.positions,
            block_table: &self.block_table,
            slot_mapping: &self.slot_mapping,
            context_lens: &self.context_lens,
            query_start_loc: &self.query_start_loc,
            seq_lens: &self.seq_lens,
            kv_caches,
            max_context_len: self.max_context_len,
            is_all_decode: self.is_all_decode,
        }
    }
}

// ─── Engine loop ─────────────────────────────────────────────────────────

/// Per-request tracking: sender channel + optional in-flight counter.
struct RequestState {
    sender: tokio::sync::mpsc::Sender<GeneratedToken>,
    in_flight_counter: Option<Arc<std::sync::atomic::AtomicUsize>>,
}

impl Drop for RequestState {
    fn drop(&mut self) {
        // Decrement in-flight counter when this request is cleaned up
        if let Some(counter) = &self.in_flight_counter {
            counter.fetch_sub(1, Ordering::Relaxed);
        }
    }
}

struct ServingEngineInner {
    scheduler: Scheduler,
    model: Box<dyn ModelRunner>,
    kv_caches: Vec<(Tensor, Tensor)>,
    device: Device,
    eos_token_id: u32,
    /// Per-sequence request state (sender + in-flight counter).
    token_senders: HashMap<SeqId, RequestState>,
    /// Receives new requests from HTTP handlers.
    request_rx: std::sync::mpsc::Receiver<EngineRequest>,
    /// Shutdown signal.
    shutdown: Arc<AtomicBool>,
    /// Speculative decoding state (if draft model is loaded).
    speculative: Option<SpeculativeState>,
}

impl ServingEngineInner {
    /// Main continuous batching loop.
    fn run(&mut self) {
        tracing::info!("Serving engine loop started");

        loop {
            if self.shutdown.load(Ordering::Acquire) {
                tracing::info!("Engine loop: shutdown signal received");
                break;
            }

            // 1. Drain new requests from the channel
            self.drain_requests();

            // 2. Check for cancelled sequences (client disconnected)
            self.check_cancellations();

            // 3. If no work, block-wait briefly for new requests
            if !self.scheduler.has_work() {
                match self
                    .request_rx
                    .recv_timeout(std::time::Duration::from_millis(10))
                {
                    Ok(req) => self.add_request(req),
                    Err(std::sync::mpsc::RecvTimeoutError::Timeout) => continue,
                    Err(std::sync::mpsc::RecvTimeoutError::Disconnected) => {
                        tracing::info!("Engine loop: request channel closed");
                        break;
                    }
                }
                continue;
            }

            // 4. Run one scheduling step
            let output = self.scheduler.schedule();
            if output.is_empty() {
                std::thread::sleep(std::time::Duration::from_millis(1));
                continue;
            }

            // 5. Clean up finished sequences
            self.handle_finished(&output);

            // 6. Build batch, run forward, sample, distribute
            //    If speculative decoding is enabled and all sequences are in
            //    decode mode, use the speculative path for better latency.
            let is_all_decode = output
                .scheduled
                .iter()
                .all(|s| !s.is_first_schedule);
            let use_speculative = is_all_decode && self.speculative.is_some();

            let step_result = if use_speculative {
                self.run_speculative_step(&output)
            } else {
                let result = self.run_step(&output);
                // After normal step, sync draft model for newly prefilled sequences
                if result.is_ok() {
                    if let Err(e) = self.run_draft_prefill_for_new_sequences(&output) {
                        tracing::warn!("Draft prefill sync failed: {e}");
                    }
                }
                result
            };

            if let Err(e) = step_result {
                tracing::error!("Forward pass failed: {e}");
                // Cancel all sequences in this batch and notify clients
                for sched in &output.scheduled {
                    self.scheduler
                        .finish_sequence(sched.seq_id, FinishReason::Cancelled);
                    if let Some(rs) = self.token_senders.remove(&sched.seq_id) {
                        let _ = rs.sender.try_send(GeneratedToken {
                            token_id: 0,
                            finish_reason: Some(FinishReason::Cancelled),
                        });
                        // rs is dropped here → decrements in_flight counter
                    }
                    if let Some(spec) = &mut self.speculative {
                        spec.remove_sequence(sched.seq_id);
                    }
                }
            }
        }

        tracing::info!("Serving engine loop exited");
    }

    /// Drain all pending requests from the channel.
    fn drain_requests(&mut self) {
        while let Ok(req) = self.request_rx.try_recv() {
            self.add_request(req);
        }
    }

    /// Add a single request to the scheduler.
    fn add_request(&mut self, req: EngineRequest) {
        let seq_id = self
            .scheduler
            .add_request(req.prompt_tokens, req.sampling_params);
        self.token_senders.insert(seq_id, RequestState {
            sender: req.token_sender,
            in_flight_counter: req.in_flight_counter,
        });

        // Track sequence in speculative state if enabled
        if let Some(spec) = &mut self.speculative {
            spec.add_sequence(seq_id);
        }

        tracing::debug!("Sequence {seq_id} added to scheduler");
    }

    /// Cancel sequences whose client has disconnected.
    fn check_cancellations(&mut self) {
        let cancelled: Vec<SeqId> = self
            .token_senders
            .iter()
            .filter(|(_, rs)| rs.sender.is_closed())
            .map(|(&id, _)| id)
            .collect();

        for seq_id in cancelled {
            tracing::debug!("Sequence {seq_id} cancelled (client disconnected)");
            self.scheduler.cancel_request(seq_id);
            self.token_senders.remove(&seq_id);
        }
    }

    /// Remove finished sequences from the scheduler and clean up senders.
    fn handle_finished(&mut self, output: &SchedulerOutput) {
        for &seq_id in &output.finished {
            self.token_senders.remove(&seq_id);
            self.scheduler.remove_finished(seq_id);

            // Clean up draft blocks if speculative decoding is active
            if let Some(spec) = &mut self.speculative {
                spec.remove_sequence(seq_id);
            }

            tracing::debug!("Sequence {seq_id} cleaned up");
        }
    }

    /// Build batch, run forward pass, sample tokens, distribute results.
    fn run_step(&mut self, output: &SchedulerOutput) -> CandleResult<()> {
        let batch = self.build_batch(output)?;
        let ctx = batch.forward_context(&self.kv_caches);
        let logits = self.model.forward(&batch.input_ids, &ctx)?;
        self.sample_and_distribute(output, &logits)
    }

    /// Build batched input tensors from the scheduler output.
    fn build_batch(&self, output: &SchedulerOutput) -> CandleResult<BatchInput> {
        let mut all_input_ids: Vec<u32> = Vec::new();
        let mut all_positions: Vec<u32> = Vec::new();
        let mut all_slot_mapping: Vec<u32> = Vec::new();
        let mut query_start_loc: Vec<usize> = vec![0];
        let mut seq_lens: Vec<usize> = Vec::new();
        let mut block_tables: Vec<Vec<u32>> = Vec::new();
        let mut context_lens_vec: Vec<u32> = Vec::new();
        let mut max_context_len: usize = 0;
        let mut is_all_decode = true;

        let kv_cache = self.scheduler.kv_cache();

        for sched in &output.scheduled {
            let seq = match self.scheduler.get_sequence(sched.seq_id) {
                Some(s) => s,
                None => {
                    tracing::warn!("Sequence {} not found in build_batch, skipping", sched.seq_id);
                    continue;
                }
            };

            // Input tokens for this step
            let input_tokens = seq.get_input_tokens_owned(sched.num_tokens);
            let start_pos = seq.num_computed_tokens();

            // Positions: [start_pos, start_pos+1, ..., start_pos+num_tokens-1]
            let positions: Vec<u32> = (start_pos..start_pos + sched.num_tokens)
                .map(|p| p as u32)
                .collect();

            // Slot mapping: physical cache slot for each new token
            let slots = kv_cache.compute_slot_mapping(&seq.blocks, start_pos, sched.num_tokens);
            let slots_u32: Vec<u32> = slots.iter().map(|&s| s as u32).collect();

            // Block table: logical block → physical block ID
            let table = kv_cache.block_table(&seq.blocks);

            // Context length = computed + new tokens
            let ctx_len = start_pos + sched.num_tokens;

            if sched.num_tokens > 1 {
                is_all_decode = false;
            }

            max_context_len = max_context_len.max(ctx_len);

            all_input_ids.extend_from_slice(&input_tokens);
            all_positions.extend_from_slice(&positions);
            all_slot_mapping.extend_from_slice(&slots_u32);
            query_start_loc.push(query_start_loc.last().unwrap() + sched.num_tokens);
            seq_lens.push(ctx_len);
            context_lens_vec.push(ctx_len as u32);
            block_tables.push(table);
        }

        // Pad block tables to uniform width for the 2D tensor
        let max_blocks = block_tables.iter().map(|t| t.len()).max().unwrap_or(1);
        let num_seqs = output.scheduled.len();
        let mut flat_block_table: Vec<u32> = Vec::with_capacity(num_seqs * max_blocks);
        for table in &block_tables {
            flat_block_table.extend_from_slice(table);
            // Pad with zeros
            flat_block_table.resize(flat_block_table.len() + max_blocks - table.len(), 0);
        }

        // Create tensors on the model's device
        let input_ids = Tensor::new(all_input_ids.as_slice(), &self.device)?;
        let positions = Tensor::new(all_positions.as_slice(), &self.device)?;
        let slot_mapping = Tensor::new(all_slot_mapping.as_slice(), &self.device)?;
        let context_lens = Tensor::new(context_lens_vec.as_slice(), &self.device)?;
        let block_table = Tensor::new(flat_block_table.as_slice(), &self.device)?
            .reshape((num_seqs, max_blocks))?;

        Ok(BatchInput {
            input_ids,
            positions,
            slot_mapping,
            block_table,
            context_lens,
            query_start_loc,
            seq_lens,
            max_context_len,
            is_all_decode,
        })
    }

    /// Sample a token for each sequence and send results to clients.
    fn sample_and_distribute(
        &mut self,
        output: &SchedulerOutput,
        logits: &Tensor,
    ) -> CandleResult<()> {
        // logits: [total_tokens, vocab_size]
        let mut offset = 0;

        for sched in &output.scheduled {
            let seq_end = offset + sched.num_tokens;

            // Extract logits for the last token of this sequence
            let last_logits = logits.narrow(0, seq_end - 1, 1)?.squeeze(0)?;
            // Ensure F32 for sampling (model might return F16 on Metal)
            let last_logits = if last_logits.dtype() != DType::F32 {
                last_logits.to_dtype(DType::F32)?
            } else {
                last_logits
            };
            let logits_vec: Vec<f32> = last_logits.to_vec1()?;

            // Get sampling params — skip sequence if it disappeared (e.g. cancelled)
            let params = match self.scheduler.get_sequence(sched.seq_id) {
                Some(seq) => seq.sampling_params.clone(),
                None => {
                    tracing::warn!("Sequence {} vanished before sampling", sched.seq_id);
                    offset = seq_end;
                    continue;
                }
            };

            // Sample token
            let token_id = sample_token(&logits_vec, &params);

            // Log sampled token at debug level
            tracing::debug!(
                "Sampled token_id={} (step {})",
                token_id,
                sched.num_tokens,
            );

            // Update computed token count in the scheduler
            self.scheduler
                .update_after_step(sched.seq_id, sched.num_tokens);

            // Append token and check stop conditions
            let is_eos = token_id == self.eos_token_id;
            let seq = match self.scheduler.get_sequence_mut(sched.seq_id) {
                Some(s) => s,
                None => {
                    offset = seq_end;
                    continue;
                }
            };

            seq.append_token(token_id);

            let should_stop = is_eos || seq.should_stop(token_id);
            let reached_max = seq.reached_max_tokens();

            let finish_reason = if should_stop {
                Some(if is_eos {
                    FinishReason::EndOfSequence
                } else {
                    FinishReason::Stop
                })
            } else if reached_max {
                Some(FinishReason::MaxTokens)
            } else {
                None
            };

            // Send token to client
            if let Some(rs) = self.token_senders.get(&sched.seq_id) {
                let token = GeneratedToken {
                    token_id,
                    finish_reason,
                };
                if rs.sender.try_send(token).is_err() {
                    // Client disconnected — check_cancellations will handle cleanup
                }
            }

            // Mark sequence as finished if needed
            if let Some(reason) = finish_reason {
                self.scheduler.finish_sequence(sched.seq_id, reason);
            }

            offset = seq_end;
        }

        Ok(())
    }

    // ─── Speculative decoding ────────────────────────────────────────────

    /// Run draft model prefill for newly prefilled sequences.
    ///
    /// After the target model processes a sequence's prompt (first schedule),
    /// the draft model also needs to process the same prompt so its KV cache
    /// is in sync for subsequent speculative decode steps.
    fn run_draft_prefill_for_new_sequences(
        &mut self,
        output: &SchedulerOutput,
    ) -> CandleResult<()> {
        let spec = match &mut self.speculative {
            Some(s) => s,
            None => return Ok(()),
        };

        for sched in &output.scheduled {
            if !sched.is_first_schedule {
                continue;
            }

            let seq = match self.scheduler.get_sequence(sched.seq_id) {
                Some(s) => s,
                None => continue,
            };

            // Get the prompt tokens that were just prefilled
            let prompt_tokens: Vec<u32> = seq.prompt_tokens.clone();
            let num_tokens = sched.num_tokens;

            // Allocate draft KV blocks for this sequence
            let draft_blocks = match spec.draft_blocks.get_mut(&sched.seq_id) {
                Some(b) => b,
                None => {
                    tracing::warn!("Draft blocks not found for seq {}", sched.seq_id);
                    continue;
                }
            };

            let alloc_result = spec.draft_kv_manager.allocate_slots(
                draft_blocks,
                num_tokens,
                None,
            );
            if alloc_result.is_none() {
                tracing::warn!(
                    "Failed to allocate draft KV blocks for seq {}",
                    sched.seq_id
                );
                continue;
            }

            // Build draft batch input for prefill
            let start_pos = draft_blocks.num_computed_tokens;
            let input_tokens: Vec<u32> = prompt_tokens[start_pos..start_pos + num_tokens].to_vec();
            let positions: Vec<u32> = (start_pos..start_pos + num_tokens)
                .map(|p| p as u32)
                .collect();
            let slots = spec.draft_kv_manager.compute_slot_mapping(
                draft_blocks,
                start_pos,
                num_tokens,
            );
            let slots_u32: Vec<u32> = slots.iter().map(|&s| s as u32).collect();
            let table = spec.draft_kv_manager.block_table(draft_blocks);
            let ctx_len = (start_pos + num_tokens) as u32;

            let input_ids = Tensor::new(input_tokens.as_slice(), &self.device)?;
            let positions_t = Tensor::new(positions.as_slice(), &self.device)?;
            let slot_mapping = Tensor::new(slots_u32.as_slice(), &self.device)?;
            let context_lens = Tensor::new(&[ctx_len], &self.device)?;
            let max_blocks = table.len().max(1);
            let block_table = Tensor::new(table.as_slice(), &self.device)?
                .reshape((1, max_blocks))?;

            let ctx = ForwardContext {
                positions: &positions_t,
                block_table: &block_table,
                slot_mapping: &slot_mapping,
                context_lens: &context_lens,
                query_start_loc: &[0, num_tokens],
                seq_lens: &[start_pos + num_tokens],
                kv_caches: &spec.draft_kv_caches,
                max_context_len: start_pos + num_tokens,
                is_all_decode: false,
            };

            // Run draft model forward (logits discarded, only KV cache matters)
            let _logits = spec.draft_model.forward(&input_ids, &ctx)?;

            // Update draft computed tokens to match target
            draft_blocks.num_computed_tokens = start_pos + num_tokens;

            tracing::debug!(
                "Draft prefill sync complete for seq {} ({} tokens)",
                sched.seq_id,
                num_tokens
            );
        }

        Ok(())
    }

    /// Run one speculative decoding step for all-decode sequences.
    ///
    /// 1. Draft phase: K autoregressive steps with the draft model
    /// 2. Verify phase: single target model forward with K tokens per sequence
    /// 3. Accept/reject per sequence with token distribution
    fn run_speculative_step(&mut self, output: &SchedulerOutput) -> CandleResult<()> {
        let num_seqs = output.scheduled.len();
        if num_seqs == 0 {
            return Ok(());
        }

        let k = self.speculative.as_ref().unwrap().current_k;

        // ── Draft phase: K autoregressive steps ──────────────────────────

        // Collect the continuation token per sequence (the unprocessed decode token)
        let mut current_tokens: Vec<u32> = Vec::with_capacity(num_seqs);
        let mut continuation_tokens: Vec<u32> = Vec::with_capacity(num_seqs);
        for sched in &output.scheduled {
            let seq = self
                .scheduler
                .get_sequence(sched.seq_id)
                .ok_or_else(|| candle_core::Error::Msg(
                    format!("sequence {} vanished before speculative step", sched.seq_id)
                ))?;
            let last_token = seq
                .get_input_tokens_owned(1)
                .into_iter()
                .next()
                .unwrap_or(0);
            current_tokens.push(last_token);
            continuation_tokens.push(last_token);
        }

        let mut draft_tokens_per_seq: Vec<Vec<u32>> = vec![Vec::with_capacity(k); num_seqs];
        let mut draft_probs_per_seq: Vec<Vec<Vec<f32>>> =
            vec![Vec::with_capacity(k); num_seqs];

        let spec = self.speculative.as_mut().unwrap();

        for step in 0..k {
            // Allocate draft KV slots for 1 new token per sequence
            for sched in &output.scheduled {
                let draft_blocks = match spec.draft_blocks.get_mut(&sched.seq_id) {
                    Some(b) => b,
                    None => {
                        tracing::warn!("Draft blocks missing for seq {} at step {step}", sched.seq_id);
                        return self.run_step(output);
                    }
                };
                if spec
                    .draft_kv_manager
                    .allocate_slots(draft_blocks, 1, None)
                    .is_none()
                {
                    tracing::warn!(
                        "Draft KV allocation failed for seq {} at step {}",
                        sched.seq_id,
                        step
                    );
                    // Fall back to normal decode for this entire step
                    // Reset draft state and use normal path
                    for sched2 in &output.scheduled {
                        let target_computed = self
                            .scheduler
                            .get_sequence(sched2.seq_id)
                            .map_or(0, |s| s.num_computed_tokens());
                        spec.sync_after_verify(sched2.seq_id, target_computed);
                    }
                    return self.run_step(output);
                }
            }

            // Build draft batch: 1 token per sequence
            let mut all_input_ids: Vec<u32> = Vec::with_capacity(num_seqs);
            let mut all_positions: Vec<u32> = Vec::with_capacity(num_seqs);
            let mut all_slot_mapping: Vec<u32> = Vec::with_capacity(num_seqs);
            let mut query_start_loc: Vec<usize> = vec![0];
            let mut seq_lens_vec: Vec<usize> = Vec::with_capacity(num_seqs);
            let mut block_tables: Vec<Vec<u32>> = Vec::with_capacity(num_seqs);
            let mut context_lens_vec: Vec<u32> = Vec::with_capacity(num_seqs);
            let mut max_context_len: usize = 0;

            for (i, sched) in output.scheduled.iter().enumerate() {
                let draft_blocks = match spec.draft_blocks.get(&sched.seq_id) {
                    Some(b) => b,
                    None => continue,
                };

                let pos = draft_blocks.num_computed_tokens;
                let ctx_len = pos + 1;

                all_input_ids.push(current_tokens[i]);
                all_positions.push(pos as u32);

                let slot = spec
                    .draft_kv_manager
                    .compute_slot(draft_blocks, pos)
                    .ok_or_else(|| candle_core::Error::Msg(
                        format!("draft KV slot missing for seq {} pos {pos}", sched.seq_id)
                    ))?;
                all_slot_mapping.push(slot as u32);

                let table = spec.draft_kv_manager.block_table(draft_blocks);
                block_tables.push(table);

                context_lens_vec.push(ctx_len as u32);
                seq_lens_vec.push(ctx_len);
                query_start_loc.push(query_start_loc.last().unwrap() + 1);
                max_context_len = max_context_len.max(ctx_len);
            }

            // Pad block tables
            let max_blocks = block_tables.iter().map(|t| t.len()).max().unwrap_or(1);
            let mut flat_block_table: Vec<u32> =
                Vec::with_capacity(num_seqs * max_blocks);
            for table in &block_tables {
                flat_block_table.extend_from_slice(table);
                flat_block_table
                    .resize(flat_block_table.len() + max_blocks - table.len(), 0);
            }

            let input_ids = Tensor::new(all_input_ids.as_slice(), &self.device)?;
            let positions = Tensor::new(all_positions.as_slice(), &self.device)?;
            let slot_mapping = Tensor::new(all_slot_mapping.as_slice(), &self.device)?;
            let context_lens = Tensor::new(context_lens_vec.as_slice(), &self.device)?;
            let block_table =
                Tensor::new(flat_block_table.as_slice(), &self.device)?
                    .reshape((num_seqs, max_blocks))?;

            let ctx = ForwardContext {
                positions: &positions,
                block_table: &block_table,
                slot_mapping: &slot_mapping,
                context_lens: &context_lens,
                query_start_loc: &query_start_loc,
                seq_lens: &seq_lens_vec,
                kv_caches: &spec.draft_kv_caches,
                max_context_len,
                is_all_decode: true,
            };

            // Draft forward pass
            let draft_logits = spec.draft_model.forward(&input_ids, &ctx)?;

            // Sample draft tokens and record probabilities
            for (i, sched) in output.scheduled.iter().enumerate() {
                let logits_i = draft_logits.narrow(0, i, 1)?.squeeze(0)?;
                let logits_i = if logits_i.dtype() != DType::F32 {
                    logits_i.to_dtype(DType::F32)?
                } else {
                    logits_i
                };
                let logits_vec: Vec<f32> = logits_i.to_vec1()?;

                let params = match self.scheduler.get_sequence(sched.seq_id) {
                    Some(seq) => seq.sampling_params.clone(),
                    None => SamplingParams::default(),
                };

                // Apply temperature scaling and compute probabilities
                let probs = if params.temperature < 1e-7 {
                    // Greedy: put all mass on the argmax
                    let token = argmax(&logits_vec);
                    let mut p = vec![0.0f32; logits_vec.len()];
                    p[token as usize] = 1.0;
                    current_tokens[i] = token;
                    draft_tokens_per_seq[i].push(token);
                    p
                } else {
                    let inv_temp = 1.0 / params.temperature;
                    let scaled: Vec<f32> =
                        logits_vec.iter().map(|&l| l * inv_temp).collect();
                    let probs = speculative::softmax_probs(&scaled);
                    let token = sample_token(&logits_vec, &params);
                    current_tokens[i] = token;
                    draft_tokens_per_seq[i].push(token);
                    probs
                };

                draft_probs_per_seq[i].push(probs);

                // Update draft num_computed_tokens
                if let Some(draft_blocks) = spec.draft_blocks.get_mut(&sched.seq_id) {
                    draft_blocks.num_computed_tokens += 1;
                }
            }
        }

        // ── Verify phase: sequential single-token decode steps ──────────
        //
        // Run K+1 sequential forward passes through the target model, one
        // token per sequence per step.  Each step is a standard batch-1
        // decode (identical GEMM to baseline), which guarantees the same
        // floating-point results as non-speculative decode.
        //
        // verify tokens: [T0, D0, D1, ..., D_{K-1}] where T0 is continuation
        // logits from step j → used to verify token j+1:
        //   step 0 processes T0   → logits verify D0
        //   step j processes D_{j-1} → logits verify D_j
        //   step K processes D_{K-1} → logits for bonus token

        let verify_len = k + 1; // K draft + 1 continuation token

        // Build per-sequence verify token lists: [T0, D0, D1, ..., D_{K-1}]
        let mut verify_tokens_per_seq: Vec<Vec<u32>> = Vec::with_capacity(num_seqs);
        for (i, _sched) in output.scheduled.iter().enumerate() {
            let mut tokens = Vec::with_capacity(verify_len);
            tokens.push(continuation_tokens[i]);
            tokens.extend_from_slice(&draft_tokens_per_seq[i]);
            verify_tokens_per_seq.push(tokens);
        }

        // Collect target logit probabilities: target_probs_all[seq_idx][step]
        let mut target_probs_all: Vec<Vec<Vec<f32>>> =
            vec![Vec::with_capacity(verify_len); num_seqs];

        // K+1 sequential verify steps (each is a standard 1-token decode)
        for step in 0..verify_len {
            // Allocate 1 target KV slot per sequence for this step
            for sched in &output.scheduled {
                if self
                    .scheduler
                    .allocate_kv_slots(sched.seq_id, 1)
                    .is_none()
                {
                    tracing::warn!(
                        "Target KV alloc failed for speculative verify seq {} step {}",
                        sched.seq_id,
                        step,
                    );
                    return self.run_step(output);
                }
            }

            // Build a standard decode batch: 1 token per sequence
            let mut all_input_ids: Vec<u32> = Vec::with_capacity(num_seqs);
            let mut all_positions: Vec<u32> = Vec::with_capacity(num_seqs);
            let mut all_slot_mapping: Vec<u32> = Vec::with_capacity(num_seqs);
            let mut query_start_loc: Vec<usize> = vec![0];
            let mut seq_lens_vec: Vec<usize> = Vec::with_capacity(num_seqs);
            let mut block_tables: Vec<Vec<u32>> = Vec::with_capacity(num_seqs);
            let mut context_lens_vec: Vec<u32> = Vec::with_capacity(num_seqs);
            let mut max_context_len: usize = 0;

            let target_kv_cache = self.scheduler.kv_cache();

            for (i, sched) in output.scheduled.iter().enumerate() {
                let seq = self
                    .scheduler
                    .get_sequence(sched.seq_id)
                    .ok_or_else(|| candle_core::Error::Msg(
                        format!("sequence {} vanished during verify step {step}", sched.seq_id)
                    ))?;

                let pos = seq.num_computed_tokens();
                let ctx_len = pos + 1;

                all_input_ids.push(verify_tokens_per_seq[i][step]);
                all_positions.push(pos as u32);

                let slot = target_kv_cache
                    .compute_slot(&seq.blocks, pos)
                    .ok_or_else(|| candle_core::Error::Msg(
                        format!("KV slot missing for seq {} pos {pos}", sched.seq_id)
                    ))?;
                all_slot_mapping.push(slot as u32);

                block_tables.push(target_kv_cache.block_table(&seq.blocks));
                context_lens_vec.push(ctx_len as u32);
                seq_lens_vec.push(ctx_len);
                query_start_loc.push(query_start_loc.last().unwrap() + 1);
                max_context_len = max_context_len.max(ctx_len);
            }

            // Pad block tables
            let max_blocks = block_tables.iter().map(|t| t.len()).max().unwrap_or(1);
            let mut flat_block_table: Vec<u32> =
                Vec::with_capacity(num_seqs * max_blocks);
            for table in &block_tables {
                flat_block_table.extend_from_slice(table);
                flat_block_table
                    .resize(flat_block_table.len() + max_blocks - table.len(), 0);
            }

            let input_ids = Tensor::new(all_input_ids.as_slice(), &self.device)?;
            let positions = Tensor::new(all_positions.as_slice(), &self.device)?;
            let slot_mapping = Tensor::new(all_slot_mapping.as_slice(), &self.device)?;
            let context_lens = Tensor::new(context_lens_vec.as_slice(), &self.device)?;
            let block_table =
                Tensor::new(flat_block_table.as_slice(), &self.device)?
                    .reshape((num_seqs, max_blocks))?;

            let ctx = ForwardContext {
                positions: &positions,
                block_table: &block_table,
                slot_mapping: &slot_mapping,
                context_lens: &context_lens,
                query_start_loc: &query_start_loc,
                seq_lens: &seq_lens_vec,
                kv_caches: &self.kv_caches,
                max_context_len,
                is_all_decode: true,
            };

            // Single-token decode forward pass (batch=num_seqs, 1 token each)
            let logits = self.model.forward(&input_ids, &ctx)?;

            // Extract logits → probs for each sequence
            for (i, sched) in output.scheduled.iter().enumerate() {
                let logits_i = logits.narrow(0, i, 1)?.squeeze(0)?;
                let logits_i = if logits_i.dtype() != DType::F32 {
                    logits_i.to_dtype(DType::F32)?
                } else {
                    logits_i
                };
                let logits_vec: Vec<f32> = logits_i.to_vec1()?;

                let params = match self.scheduler.get_sequence(sched.seq_id) {
                    Some(seq) => seq.sampling_params.clone(),
                    None => SamplingParams::default(),
                };

                let probs = if params.temperature < 1e-7 {
                    let mut p = vec![0.0f32; logits_vec.len()];
                    p[argmax(&logits_vec) as usize] = 1.0;
                    p
                } else {
                    let inv_temp = 1.0 / params.temperature;
                    let scaled: Vec<f32> =
                        logits_vec.iter().map(|&l| l * inv_temp).collect();
                    speculative::softmax_probs(&scaled)
                };

                target_probs_all[i].push(probs);
            }

            // Advance num_computed_tokens by 1 for all sequences
            for sched in &output.scheduled {
                self.scheduler.update_after_step(sched.seq_id, 1);
            }
        }

        // ── Accept/reject per sequence ───────────────────────────────────
        //
        // target_probs_all[i] has K+1 entries:
        //   [0] = probs from processing T0 → verify D0
        //   [j] = probs from processing D_{j-1} → verify D_j
        //   [K] = probs from processing D_{K-1} → bonus token

        let spec = self.speculative.as_mut().unwrap();
        let mut total_accepted_this_step: u64 = 0;

        for (i, sched) in output.scheduled.iter().enumerate() {
            // First K entries verify draft tokens, last entry is bonus
            let target_probs_for_verify = &target_probs_all[i][..k];
            let bonus_probs = &target_probs_all[i][k];

            // Run accept/reject
            let result = speculative::accept_reject(
                target_probs_for_verify,
                &draft_probs_per_seq[i],
                &draft_tokens_per_seq[i],
                Some(bonus_probs),
            );

            total_accepted_this_step += result.num_accepted as u64;
            let num_new_tokens = result.num_accepted + 1; // accepted + final

            // The verify phase already updated num_computed_tokens by K+1.
            // We need to roll back to the correct count: only num_new_tokens
            // were actually accepted past the continuation token position.
            // The continuation token (T0) was computed (1 step), plus
            // num_accepted draft tokens + 1 final token = num_new_tokens.
            // But verify ran K+1 steps total. Roll back excess:
            let excess = verify_len - num_new_tokens;
            if excess > 0 {
                if let Some(seq) = self.scheduler.get_sequence_mut(sched.seq_id) {
                    seq.blocks.num_computed_tokens -= excess;
                }
            }

            // Sync draft state
            let target_computed = self
                .scheduler
                .get_sequence(sched.seq_id)
                .map_or(0, |s| s.num_computed_tokens());
            spec.sync_after_verify(sched.seq_id, target_computed);

            // Send all accepted tokens + final token to client
            let seq = match self.scheduler.get_sequence_mut(sched.seq_id) {
                Some(s) => s,
                None => continue,
            };

            let mut should_finish = false;
            let mut finish_reason = None;

            // Append and send accepted tokens
            for &token_id in &result.accepted_tokens {
                seq.append_token(token_id);

                let is_eos = token_id == self.eos_token_id;
                let is_stop = seq.should_stop(token_id);
                let is_max = seq.reached_max_tokens();

                let fr = if is_eos {
                    Some(FinishReason::EndOfSequence)
                } else if is_stop {
                    Some(FinishReason::Stop)
                } else if is_max {
                    Some(FinishReason::MaxTokens)
                } else {
                    None
                };

                if let Some(rs) = self.token_senders.get(&sched.seq_id) {
                    let _ = rs.sender.try_send(GeneratedToken {
                        token_id,
                        finish_reason: fr,
                    });
                }

                if fr.is_some() {
                    should_finish = true;
                    finish_reason = fr;
                    break;
                }
            }

            // Append and send the final token (bonus or resampled)
            if !should_finish {
                let token_id = result.final_token;
                seq.append_token(token_id);

                let is_eos = token_id == self.eos_token_id;
                let is_stop = seq.should_stop(token_id);
                let is_max = seq.reached_max_tokens();

                let fr = if is_eos {
                    Some(FinishReason::EndOfSequence)
                } else if is_stop {
                    Some(FinishReason::Stop)
                } else if is_max {
                    Some(FinishReason::MaxTokens)
                } else {
                    None
                };

                if let Some(rs) = self.token_senders.get(&sched.seq_id) {
                    let _ = rs.sender.try_send(GeneratedToken {
                        token_id,
                        finish_reason: fr,
                    });
                }

                if fr.is_some() {
                    should_finish = true;
                    finish_reason = fr;
                }
            }

            if should_finish {
                if let Some(reason) = finish_reason {
                    self.scheduler.finish_sequence(sched.seq_id, reason);
                }
            }

            tracing::debug!(
                "Speculative: seq {} accepted {}/{} tokens + final",
                sched.seq_id,
                result.num_accepted,
                k
            );
        }

        // Update adaptive K
        spec.total_accepted += total_accepted_this_step;
        spec.total_drafted += (num_seqs * k) as u64;
        spec.update_adaptive_k();

        Ok(())
    }
}

// ─── Token sampling ──────────────────────────────────────────────────────

/// Sample a token from logits using the given sampling parameters.
fn sample_token(logits: &[f32], params: &SamplingParams) -> u32 {
    if params.temperature < 1e-7 {
        return argmax(logits);
    }

    // Temperature scaling
    let inv_temp = 1.0 / params.temperature;
    let scaled: Vec<f32> = logits.iter().map(|&l| l * inv_temp).collect();

    // Softmax
    let probs = softmax(&scaled);

    // Top-k filtering (if enabled)
    if params.top_k > 0 && params.top_k < probs.len() {
        let filtered = top_k_filter(&probs, params.top_k);
        if params.top_p > 0.0 && params.top_p < 1.0 {
            top_p_sample(&filtered, params.top_p)
        } else {
            categorical_sample(&filtered)
        }
    } else if params.top_p > 0.0 && params.top_p < 1.0 {
        top_p_sample(&probs, params.top_p)
    } else {
        categorical_sample(&probs)
    }
}

fn argmax(logits: &[f32]) -> u32 {
    logits
        .iter()
        .enumerate()
        .max_by(|a, b| a.1.partial_cmp(b.1).unwrap_or(std::cmp::Ordering::Equal))
        .map(|(i, _)| i as u32)
        .unwrap_or(0)
}

fn softmax(logits: &[f32]) -> Vec<f32> {
    let max = logits.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
    let exp: Vec<f32> = logits.iter().map(|&l| (l - max).exp()).collect();
    let sum: f32 = exp.iter().sum();
    if sum == 0.0 {
        vec![1.0 / logits.len() as f32; logits.len()]
    } else {
        exp.iter().map(|&e| e / sum).collect()
    }
}

/// Zero out all but the top-k probabilities, then re-normalize.
fn top_k_filter(probs: &[f32], k: usize) -> Vec<f32> {
    let mut indexed: Vec<(usize, f32)> = probs.iter().enumerate().map(|(i, &p)| (i, p)).collect();
    indexed.sort_unstable_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

    let mut filtered = vec![0.0f32; probs.len()];
    let mut total = 0.0;
    for &(idx, prob) in indexed.iter().take(k) {
        filtered[idx] = prob;
        total += prob;
    }
    if total > 0.0 {
        for p in &mut filtered {
            *p /= total;
        }
    }
    filtered
}

fn top_p_sample(probs: &[f32], top_p: f32) -> u32 {
    // Sort by probability descending
    let mut indexed: Vec<(usize, f32)> = probs.iter().enumerate().map(|(i, &p)| (i, p)).collect();
    indexed.sort_unstable_by(|a, b| b.1.partial_cmp(&a.1).unwrap_or(std::cmp::Ordering::Equal));

    // Accumulate until top_p
    let mut cumsum = 0.0;
    let mut candidates: Vec<(usize, f32)> = Vec::new();
    for (idx, prob) in indexed {
        cumsum += prob;
        candidates.push((idx, prob));
        if cumsum >= top_p {
            break;
        }
    }

    // Re-normalize and sample
    let total: f32 = candidates.iter().map(|(_, p)| p).sum();
    if total == 0.0 {
        return candidates.first().map(|(i, _)| *i as u32).unwrap_or(0);
    }

    let r = pseudo_random() * total;
    let mut acc = 0.0;
    for (idx, prob) in &candidates {
        acc += prob;
        if acc >= r {
            return *idx as u32;
        }
    }

    candidates.last().map(|(i, _)| *i as u32).unwrap_or(0)
}

fn categorical_sample(probs: &[f32]) -> u32 {
    let r = pseudo_random();
    let mut acc = 0.0;
    for (i, &p) in probs.iter().enumerate() {
        acc += p;
        if acc >= r {
            return i as u32;
        }
    }
    (probs.len() - 1) as u32
}

/// Pseudo-random float in [0, 1) using thread-local xorshift64.
/// Seeded from system entropy on first use per thread.
fn pseudo_random() -> f32 {
    use std::cell::Cell;
    use std::collections::hash_map::RandomState;
    use std::hash::{BuildHasher, Hasher};
    thread_local! {
        static STATE: Cell<u64> = {
            // Seed from system entropy via RandomState (no extra deps)
            let seed = RandomState::new().build_hasher().finish();
            // Ensure nonzero (xorshift requires nonzero state)
            Cell::new(seed | 1)
        };
    }
    STATE.with(|s| {
        let mut x = s.get();
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        s.set(x);
        (x >> 11) as f32 / (1u64 << 53) as f32
    })
}

// ─── KV cache allocation ─────────────────────────────────────────────────

/// Allocate per-layer KV cache tensor pairs.
///
/// K cache layout: `[num_blocks, num_kv_heads, head_size/x, block_size, x]`
/// V cache layout: `[num_blocks, num_kv_heads, head_size, block_size]`
///
/// where `x = 16 / dtype_size` is the vectorization factor.
fn allocate_kv_caches(
    num_layers: usize,
    num_blocks: usize,
    num_kv_heads: usize,
    head_size: usize,
    dtype: DType,
    device: &Device,
) -> CandleResult<Vec<(Tensor, Tensor)>> {
    let x = 16 / dtype.size_in_bytes();
    let mut caches = Vec::with_capacity(num_layers);

    for _ in 0..num_layers {
        let key_cache = Tensor::zeros(
            (num_blocks, num_kv_heads, head_size / x, BLOCK_SIZE, x),
            dtype,
            device,
        )?;
        let value_cache = Tensor::zeros(
            (num_blocks, num_kv_heads, head_size, BLOCK_SIZE),
            dtype,
            device,
        )?;
        caches.push((key_cache, value_cache));
    }

    Ok(caches)
}

// ─── Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::serving::models::ModelConfig;

    // ── Sampling tests ───────────────────────────────────────────────────

    #[test]
    fn test_argmax() {
        assert_eq!(argmax(&[1.0, 3.0, 2.0]), 1);
        assert_eq!(argmax(&[5.0, 1.0, 2.0]), 0);
        assert_eq!(argmax(&[1.0, 2.0, 3.0]), 2);
    }

    #[test]
    fn test_argmax_single() {
        assert_eq!(argmax(&[42.0]), 0);
    }

    #[test]
    fn test_softmax() {
        let probs = softmax(&[1.0, 2.0, 3.0]);
        assert_eq!(probs.len(), 3);
        let sum: f32 = probs.iter().sum();
        assert!((sum - 1.0).abs() < 1e-5);
        assert!(probs[0] < probs[1]);
        assert!(probs[1] < probs[2]);
    }

    #[test]
    fn test_softmax_uniform() {
        let probs = softmax(&[0.0, 0.0, 0.0]);
        let sum: f32 = probs.iter().sum();
        assert!((sum - 1.0).abs() < 1e-5);
        assert!((probs[0] - probs[1]).abs() < 1e-5);
    }

    #[test]
    fn test_softmax_large_values() {
        // Should not overflow thanks to max subtraction
        let probs = softmax(&[1000.0, 1001.0, 999.0]);
        let sum: f32 = probs.iter().sum();
        assert!((sum - 1.0).abs() < 1e-5);
    }

    #[test]
    fn test_sample_greedy() {
        let params = SamplingParams {
            temperature: 0.0,
            ..SamplingParams::default()
        };
        assert_eq!(sample_token(&[1.0, 5.0, 3.0, 2.0], &params), 1);
        assert_eq!(sample_token(&[10.0, 1.0, 2.0], &params), 0);
    }

    #[test]
    fn test_top_k_filter() {
        let probs = vec![0.1, 0.5, 0.3, 0.1];
        let filtered = top_k_filter(&probs, 2);
        // Top 2: index 1 (0.5) and index 2 (0.3)
        assert_eq!(filtered[0], 0.0);
        assert!(filtered[1] > 0.0);
        assert!(filtered[2] > 0.0);
        assert_eq!(filtered[3], 0.0);
        let sum: f32 = filtered.iter().sum();
        assert!((sum - 1.0).abs() < 1e-5);
    }

    #[test]
    fn test_top_p_sample_deterministic() {
        // All probability mass on index 2
        let probs = vec![0.0, 0.0, 1.0, 0.0];
        assert_eq!(top_p_sample(&probs, 0.99), 2);
    }

    #[test]
    fn test_pseudo_random_range() {
        for _ in 0..1000 {
            let r = pseudo_random();
            assert!(
                (0.0..1.0).contains(&r),
                "random value out of range: {r}"
            );
        }
    }

    #[test]
    fn test_categorical_sample_deterministic() {
        // All mass on one token
        let probs = vec![0.0, 0.0, 0.0, 1.0];
        assert_eq!(categorical_sample(&probs), 3);
    }

    // ── KV cache tests ───────────────────────────────────────────────────

    #[test]
    fn test_allocate_kv_caches_cpu() {
        let caches = allocate_kv_caches(2, 4, 8, 128, DType::F32, &Device::Cpu).unwrap();
        assert_eq!(caches.len(), 2);

        let x = 16 / DType::F32.size_in_bytes(); // x = 4
        let (k, v) = &caches[0];
        assert_eq!(k.dims(), &[4, 8, 128 / x, BLOCK_SIZE, x]);
        assert_eq!(v.dims(), &[4, 8, 128, BLOCK_SIZE]);
    }

    #[test]
    fn test_allocate_kv_caches_shapes() {
        let caches = allocate_kv_caches(1, 2, 4, 64, DType::F32, &Device::Cpu).unwrap();
        let x = 16 / DType::F32.size_in_bytes(); // x = 4
        let (k, v) = &caches[0];
        assert_eq!(k.dims(), &[2, 4, 64 / x, BLOCK_SIZE, x]);
        assert_eq!(v.dims(), &[2, 4, 64, BLOCK_SIZE]);
    }

    // ── BatchInput tests ─────────────────────────────────────────────────

    #[test]
    fn test_batch_input_forward_context() {
        let device = Device::Cpu;

        let input_ids = Tensor::new(&[1u32, 2, 3], &device).unwrap();
        let positions = Tensor::new(&[0u32, 1, 2], &device).unwrap();
        let slot_mapping = Tensor::new(&[0u32, 1, 2], &device).unwrap();
        let block_table = Tensor::new(&[0u32], &device)
            .unwrap()
            .reshape((1, 1))
            .unwrap();
        let context_lens = Tensor::new(&[3u32], &device).unwrap();

        let batch = BatchInput {
            input_ids,
            positions,
            slot_mapping,
            block_table,
            context_lens,
            query_start_loc: vec![0, 3],
            seq_lens: vec![3],
            max_context_len: 3,
            is_all_decode: false,
        };

        let kv_caches = allocate_kv_caches(1, 4, 8, 128, DType::F32, &device).unwrap();
        let ctx = batch.forward_context(&kv_caches);

        assert_eq!(ctx.max_context_len, 3);
        assert!(!ctx.is_all_decode);
        assert_eq!(ctx.seq_lens, &[3]);
        assert_eq!(ctx.query_start_loc, &[0, 3]);
    }

    #[test]
    fn test_batch_input_decode_mode() {
        let device = Device::Cpu;

        // Two sequences, each with 1 token (decode mode)
        let input_ids = Tensor::new(&[42u32, 99], &device).unwrap();
        let positions = Tensor::new(&[10u32, 5], &device).unwrap();
        let slot_mapping = Tensor::new(&[160u32, 80], &device).unwrap();
        let block_table = Tensor::new(&[0u32, 0, 1, 0], &device)
            .unwrap()
            .reshape((2, 2))
            .unwrap();
        let context_lens = Tensor::new(&[11u32, 6], &device).unwrap();

        let batch = BatchInput {
            input_ids,
            positions,
            slot_mapping,
            block_table,
            context_lens,
            query_start_loc: vec![0, 1, 2],
            seq_lens: vec![11, 6],
            max_context_len: 11,
            is_all_decode: true,
        };

        let kv_caches = allocate_kv_caches(1, 4, 8, 128, DType::F32, &device).unwrap();
        let ctx = batch.forward_context(&kv_caches);

        assert!(ctx.is_all_decode);
        assert_eq!(ctx.max_context_len, 11);
        assert_eq!(ctx.seq_lens, &[11, 6]);
    }

    // ── Public type tests ────────────────────────────────────────────────

    #[test]
    fn test_generated_token_debug() {
        let token = GeneratedToken {
            token_id: 42,
            finish_reason: Some(FinishReason::EndOfSequence),
        };
        let s = format!("{:?}", token);
        assert!(s.contains("42"));
    }

    #[test]
    fn test_engine_error_display() {
        let err = EngineError::Shutdown;
        assert_eq!(format!("{err}"), "engine has shut down");
        assert!(err.to_string().contains("shut down"));
    }

    #[test]
    fn test_serving_engine_config_default() {
        let config = ServingEngineConfig::default();
        assert_eq!(config.max_num_seqs, 64);
        assert_eq!(config.max_num_batched_tokens, 2048);
        assert_eq!(config.num_kv_cache_blocks, 256);
        assert!(config.enable_prefix_cache);
    }

    // ── Integration test with mock model ─────────────────────────────────

    /// Mock model that returns fixed logits (always predicts token 42).
    struct MockModel {
        config: ModelConfig,
    }

    impl MockModel {
        fn new() -> Self {
            Self {
                config: ModelConfig {
                    hidden_size: 64,
                    intermediate_size: 256,
                    num_heads: 4,
                    num_kv_heads: 4,
                    num_layers: 2,
                    head_size: 16,
                    vocab_size: 100,
                    rms_norm_eps: 1e-5,
                    rope_theta: 10000.0,
                    rope_dim: 16,
                    max_seq_len: 128,
                },
            }
        }
    }

    impl ModelRunner for MockModel {
        fn forward(&self, input_ids: &Tensor, _ctx: &ForwardContext) -> CandleResult<Tensor> {
            let total_tokens = input_ids.dims()[0];
            let vocab_size = self.config.vocab_size;
            // Return logits where token 42 has highest score
            let mut logits = vec![0.0f32; total_tokens * vocab_size];
            for t in 0..total_tokens {
                logits[t * vocab_size + 42] = 10.0;
            }
            Tensor::new(logits.as_slice(), input_ids.device())?
                .reshape((total_tokens, vocab_size))
        }

        fn num_layers(&self) -> usize {
            self.config.num_layers
        }
        fn num_kv_heads(&self) -> usize {
            self.config.num_kv_heads
        }
        fn head_size(&self) -> usize {
            self.config.head_size
        }
        fn num_heads(&self) -> usize {
            self.config.num_heads
        }
        fn config(&self) -> &ModelConfig {
            &self.config
        }
    }

    #[test]
    fn test_engine_with_mock_model() {
        // Create a mock tokenizer (minimal — just needs to exist)
        let tokenizer = Tokenizer::from_bytes(MINIMAL_TOKENIZER_JSON.as_bytes()).unwrap();

        let handle = EngineHandle::start(
            Box::new(MockModel::new()),
            tokenizer,
            0, // EOS token
            Device::Cpu,
            ServingEngineConfig {
                max_num_seqs: 4,
                max_num_batched_tokens: 128,
                num_kv_cache_blocks: 8,
                enable_prefix_cache: false,
            },
        )
        .unwrap();

        // Submit a request
        let mut rx = handle
            .submit(
                vec![1, 2, 3, 4, 5],
                SamplingParams {
                    temperature: 0.0, // greedy
                    max_tokens: 3,
                    ..SamplingParams::default()
                },
            )
            .unwrap();

        // Collect tokens (blocking on the tokio receiver)
        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();

        let tokens: Vec<GeneratedToken> = rt.block_on(async {
            let mut tokens = Vec::new();
            while let Some(tok) = rx.recv().await {
                let done = tok.finish_reason.is_some();
                tokens.push(tok);
                if done {
                    break;
                }
            }
            tokens
        });

        // Should have generated 3 tokens (max_tokens=3), all token 42
        assert!(!tokens.is_empty());
        for tok in &tokens {
            assert_eq!(tok.token_id, 42, "mock model always predicts token 42");
        }
        // Last token should have finish reason
        let last = tokens.last().unwrap();
        assert!(last.finish_reason.is_some());

        handle.shutdown();
    }

    /// Minimal valid tokenizer JSON for testing.
    const MINIMAL_TOKENIZER_JSON: &str = r#"{
        "version": "1.0",
        "truncation": null,
        "padding": null,
        "added_tokens": [],
        "normalizer": null,
        "pre_tokenizer": null,
        "post_processor": null,
        "decoder": null,
        "model": {
            "type": "BPE",
            "dropout": null,
            "unk_token": null,
            "continuing_subword_prefix": null,
            "end_of_word_suffix": null,
            "fuse_unk": false,
            "byte_fallback": false,
            "vocab": {},
            "merges": []
        }
    }"#;

    // ── Speculative decoding integration tests ──────────────────────────

    #[test]
    fn test_engine_with_speculative_decoding() {
        use crate::serving::speculative::{SpeculativeConfig, SpeculativeState};

        let tokenizer = Tokenizer::from_bytes(MINIMAL_TOKENIZER_JSON.as_bytes()).unwrap();

        let target_model = Box::new(MockModel::new());
        let draft_model = Box::new(MockModel::new()); // Same model = 100% acceptance

        let device = Device::Cpu;
        let spec_config = SpeculativeConfig {
            num_draft_tokens: 3,
            adaptive: false,
            min_draft_tokens: 1,
            max_draft_tokens: 8,
        };

        let speculative = SpeculativeState::new(
            draft_model,
            &device,
            8, // draft KV blocks
            spec_config,
        )
        .unwrap();

        let handle = EngineHandle::start_with_draft(
            target_model,
            tokenizer,
            0, // EOS token
            device,
            ServingEngineConfig {
                max_num_seqs: 4,
                max_num_batched_tokens: 128,
                num_kv_cache_blocks: 8,
                enable_prefix_cache: false,
            },
            speculative,
        )
        .unwrap();

        // Submit a request
        let mut rx = handle
            .submit(
                vec![1, 2, 3, 4, 5],
                SamplingParams {
                    temperature: 0.0, // greedy
                    max_tokens: 6,
                    ..SamplingParams::default()
                },
            )
            .unwrap();

        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();

        let tokens: Vec<GeneratedToken> = rt.block_on(async {
            let mut tokens = Vec::new();
            while let Some(tok) = rx.recv().await {
                let done = tok.finish_reason.is_some();
                tokens.push(tok);
                if done {
                    break;
                }
            }
            tokens
        });

        // Should generate tokens (mock model always predicts token 42)
        assert!(!tokens.is_empty(), "should have generated some tokens");
        for tok in &tokens {
            assert_eq!(tok.token_id, 42, "mock model always predicts token 42");
        }
        // Last token should have finish reason (max_tokens reached)
        let last = tokens.last().unwrap();
        assert!(last.finish_reason.is_some());

        handle.shutdown();
    }

    #[test]
    fn test_speculative_with_different_draft_model() {
        use crate::serving::speculative::{SpeculativeConfig, SpeculativeState};

        /// Mock model that always predicts token 99 (differs from target's 42).
        /// This should trigger rejection in speculative decoding.
        struct DraftModel99 {
            config: ModelConfig,
        }

        impl DraftModel99 {
            fn new() -> Self {
                Self {
                    config: ModelConfig {
                        hidden_size: 64,
                        intermediate_size: 256,
                        num_heads: 4,
                        num_kv_heads: 4,
                        num_layers: 2,
                        head_size: 16,
                        vocab_size: 100,
                        rms_norm_eps: 1e-5,
                        rope_theta: 10000.0,
                        rope_dim: 16,
                        max_seq_len: 128,
                    },
                }
            }
        }

        impl ModelRunner for DraftModel99 {
            fn forward(
                &self,
                input_ids: &Tensor,
                _ctx: &ForwardContext,
            ) -> CandleResult<Tensor> {
                let total_tokens = input_ids.dims()[0];
                let vocab_size = self.config.vocab_size;
                let mut logits = vec![0.0f32; total_tokens * vocab_size];
                for t in 0..total_tokens {
                    logits[t * vocab_size + 99] = 10.0; // Predict token 99
                }
                Tensor::new(logits.as_slice(), input_ids.device())?
                    .reshape((total_tokens, vocab_size))
            }
            fn num_layers(&self) -> usize {
                self.config.num_layers
            }
            fn num_kv_heads(&self) -> usize {
                self.config.num_kv_heads
            }
            fn head_size(&self) -> usize {
                self.config.head_size
            }
            fn num_heads(&self) -> usize {
                self.config.num_heads
            }
            fn config(&self) -> &ModelConfig {
                &self.config
            }
        }

        let tokenizer = Tokenizer::from_bytes(MINIMAL_TOKENIZER_JSON.as_bytes()).unwrap();

        let target_model = Box::new(MockModel::new()); // predicts 42
        let draft_model = Box::new(DraftModel99::new()); // predicts 99

        let device = Device::Cpu;
        let spec_config = SpeculativeConfig {
            num_draft_tokens: 3,
            adaptive: false,
            min_draft_tokens: 1,
            max_draft_tokens: 8,
        };

        let speculative = SpeculativeState::new(
            draft_model,
            &device,
            8,
            spec_config,
        )
        .unwrap();

        let handle = EngineHandle::start_with_draft(
            target_model,
            tokenizer,
            0,
            device,
            ServingEngineConfig {
                max_num_seqs: 4,
                max_num_batched_tokens: 128,
                num_kv_cache_blocks: 8,
                enable_prefix_cache: false,
            },
            speculative,
        )
        .unwrap();

        let mut rx = handle
            .submit(
                vec![1, 2, 3],
                SamplingParams {
                    temperature: 0.0, // greedy
                    max_tokens: 4,
                    ..SamplingParams::default()
                },
            )
            .unwrap();

        let rt = tokio::runtime::Builder::new_current_thread()
            .enable_all()
            .build()
            .unwrap();

        let tokens: Vec<GeneratedToken> = rt.block_on(async {
            let mut tokens = Vec::new();
            while let Some(tok) = rx.recv().await {
                let done = tok.finish_reason.is_some();
                tokens.push(tok);
                if done {
                    break;
                }
            }
            tokens
        });

        // Should still complete (rejection → resampling from target distribution)
        assert!(!tokens.is_empty(), "should have generated tokens");
        // With greedy sampling, target model always predicts 42
        // Draft predicts 99 → rejected → resample from adjusted dist
        // The adjusted distribution should favor 42 (target's preference)
        let last = tokens.last().unwrap();
        assert!(last.finish_reason.is_some());

        handle.shutdown();
    }
}
