//! Thin FFI bindings to NVIDIA NCCL (Collective Communications Library).
//!
//! These bindings are only compiled when the `cuda` feature is enabled.
//! On non-CUDA builds, this module provides stub types so the rest of the
//! tensor parallelism code can reference `NcclComm` without cfg-gating
//! every callsite.
//!
//! NCCL is used for AllReduce and AllGather across GPUs in tensor parallel
//! inference. Each GPU rank holds a shard of the model weights and
//! communicates partial results via NCCL collectives.

use candle_core::Result;

// ─── NCCL unique ID size ──────────────────────────────────────────────────

/// Size of the NCCL unique ID (128 bytes as per NCCL API).
pub const NCCL_UNIQUE_ID_BYTES: usize = 128;

// ─── CUDA FFI bindings ────────────────────────────────────────────────────

#[cfg(feature = "cuda")]
mod ffi {
    use std::os::raw::{c_int, c_void};

    /// NCCL result type.
    pub type NcclResult = c_int;
    pub const NCCL_SUCCESS: NcclResult = 0;

    /// NCCL data type for f16.
    pub const NCCL_FLOAT16: c_int = 6;
    /// NCCL data type for f32.
    pub const NCCL_FLOAT32: c_int = 7;

    /// NCCL reduction operation: sum.
    pub const NCCL_SUM: c_int = 0;

    /// Opaque NCCL communicator handle.
    pub type NcclComm = *mut c_void;

    /// Opaque CUDA stream handle.
    pub type CudaStream = *mut c_void;

    #[repr(C)]
    pub struct NcclUniqueId {
        pub internal: [u8; super::NCCL_UNIQUE_ID_BYTES],
    }

    #[link(name = "nccl")]
    extern "C" {
        pub fn ncclGetUniqueId(unique_id: *mut NcclUniqueId) -> NcclResult;
        pub fn ncclCommInitRank(
            comm: *mut NcclComm,
            nranks: c_int,
            unique_id: NcclUniqueId,
            rank: c_int,
        ) -> NcclResult;
        pub fn ncclCommDestroy(comm: NcclComm) -> NcclResult;
        pub fn ncclAllReduce(
            sendbuf: *const c_void,
            recvbuf: *mut c_void,
            count: usize,
            datatype: c_int,
            op: c_int,
            comm: NcclComm,
            stream: CudaStream,
        ) -> NcclResult;
        pub fn ncclAllGather(
            sendbuf: *const c_void,
            recvbuf: *mut c_void,
            sendcount: usize,
            datatype: c_int,
            comm: NcclComm,
            stream: CudaStream,
        ) -> NcclResult;
    }
}

// ─── Safe NCCL communicator wrapper ───────────────────────────────────────

/// Safe wrapper around an NCCL communicator.
///
/// On CUDA builds, this holds a real NCCL communicator handle.
/// On non-CUDA builds, this is an empty struct that exists only so
/// `TensorParallelGroup` can reference it without conditional compilation.
#[cfg(feature = "cuda")]
pub struct NcclComm {
    handle: ffi::NcclComm,
    rank: usize,
    world_size: usize,
}

#[cfg(not(feature = "cuda"))]
#[derive(Debug)]
pub struct NcclComm {
    rank: usize,
    world_size: usize,
}

// SAFETY: NCCL communicators are thread-safe for non-overlapping operations.
// The engine loop serializes all collective calls per step.
unsafe impl Send for NcclComm {}
unsafe impl Sync for NcclComm {}

impl NcclComm {
    /// Initialize an NCCL communicator for the given rank in a world.
    ///
    /// # Arguments
    /// - `nccl_id`: The unique ID bytes (128 bytes) generated by the rank-0 process.
    /// - `world_size`: Total number of participating GPUs.
    /// - `rank`: This GPU's rank (0..world_size-1).
    #[cfg(feature = "cuda")]
    pub fn init(nccl_id: &[u8], world_size: usize, rank: usize) -> Result<Self> {
        if nccl_id.len() != NCCL_UNIQUE_ID_BYTES {
            return Err(candle_core::Error::Msg(format!(
                "NCCL unique ID must be {} bytes, got {}",
                NCCL_UNIQUE_ID_BYTES,
                nccl_id.len()
            )));
        }

        let mut unique_id = ffi::NcclUniqueId {
            internal: [0u8; NCCL_UNIQUE_ID_BYTES],
        };
        unique_id.internal.copy_from_slice(nccl_id);

        let mut comm: ffi::NcclComm = std::ptr::null_mut();
        let result = unsafe {
            ffi::ncclCommInitRank(
                &mut comm,
                world_size as std::os::raw::c_int,
                unique_id,
                rank as std::os::raw::c_int,
            )
        };

        if result != ffi::NCCL_SUCCESS {
            return Err(candle_core::Error::Msg(format!(
                "ncclCommInitRank failed with error code {result}"
            )));
        }

        Ok(Self {
            handle: comm,
            rank,
            world_size,
        })
    }

    /// Stub initializer for non-CUDA builds. Always returns an error.
    #[cfg(not(feature = "cuda"))]
    pub fn init(_nccl_id: &[u8], world_size: usize, rank: usize) -> Result<Self> {
        if world_size > 1 {
            return Err(candle_core::Error::Msg(
                "NCCL communicator requires the 'cuda' feature. \
                 Tensor parallelism with world_size > 1 is not available on CPU/Metal."
                    .to_string(),
            ));
        }
        Ok(Self { rank, world_size })
    }

    /// Generate a new NCCL unique ID (only valid on rank 0).
    #[cfg(feature = "cuda")]
    pub fn get_unique_id() -> Result<Vec<u8>> {
        let mut unique_id = ffi::NcclUniqueId {
            internal: [0u8; NCCL_UNIQUE_ID_BYTES],
        };
        let result = unsafe { ffi::ncclGetUniqueId(&mut unique_id) };
        if result != ffi::NCCL_SUCCESS {
            return Err(candle_core::Error::Msg(format!(
                "ncclGetUniqueId failed with error code {result}"
            )));
        }
        Ok(unique_id.internal.to_vec())
    }

    /// Stub for non-CUDA builds.
    #[cfg(not(feature = "cuda"))]
    pub fn get_unique_id() -> Result<Vec<u8>> {
        // Return dummy bytes for single-rank "TP" on CPU
        Ok(vec![0u8; NCCL_UNIQUE_ID_BYTES])
    }

    /// AllReduce sum: sum `input` across all ranks, writing result to `output`.
    ///
    /// On non-CUDA builds with world_size=1, this is a no-op (identity).
    #[cfg(feature = "cuda")]
    pub fn all_reduce_sum_f32(
        &self,
        input: *const std::ffi::c_void,
        output: *mut std::ffi::c_void,
        count: usize,
        stream: *mut std::ffi::c_void,
    ) -> Result<()> {
        let result = unsafe {
            ffi::ncclAllReduce(
                input,
                output,
                count,
                ffi::NCCL_FLOAT32,
                ffi::NCCL_SUM,
                self.handle,
                stream,
            )
        };
        if result != ffi::NCCL_SUCCESS {
            return Err(candle_core::Error::Msg(format!(
                "ncclAllReduce failed with error code {result}"
            )));
        }
        Ok(())
    }

    /// AllGather: gather `input` from each rank into `output` (world_size * count elements).
    #[cfg(feature = "cuda")]
    pub fn all_gather_f32(
        &self,
        input: *const std::ffi::c_void,
        output: *mut std::ffi::c_void,
        send_count: usize,
        stream: *mut std::ffi::c_void,
    ) -> Result<()> {
        let result = unsafe {
            ffi::ncclAllGather(
                input,
                output,
                send_count,
                ffi::NCCL_FLOAT32,
                self.handle,
                stream,
            )
        };
        if result != ffi::NCCL_SUCCESS {
            return Err(candle_core::Error::Msg(format!(
                "ncclAllGather failed with error code {result}"
            )));
        }
        Ok(())
    }

    /// This GPU's rank.
    pub fn rank(&self) -> usize {
        self.rank
    }

    /// Total number of GPUs in this communicator.
    pub fn world_size(&self) -> usize {
        self.world_size
    }
}

#[cfg(feature = "cuda")]
impl Drop for NcclComm {
    fn drop(&mut self) {
        if !self.handle.is_null() {
            unsafe {
                ffi::ncclCommDestroy(self.handle);
            }
        }
    }
}

// ─── Tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_unique_id_generation() {
        let id = NcclComm::get_unique_id().unwrap();
        assert_eq!(id.len(), NCCL_UNIQUE_ID_BYTES);
    }

    #[test]
    fn test_single_rank_init() {
        // Single-rank communicator should work on all platforms
        let id = NcclComm::get_unique_id().unwrap();
        let comm = NcclComm::init(&id, 1, 0).unwrap();
        assert_eq!(comm.rank(), 0);
        assert_eq!(comm.world_size(), 1);
    }

    #[test]
    fn test_invalid_nccl_id_length() {
        let short_id = vec![0u8; 64]; // Too short
        let result = NcclComm::init(&short_id, 1, 0);
        // On non-CUDA with world_size=1, the stub doesn't validate ID length
        // On CUDA, this would fail with invalid length
        #[cfg(feature = "cuda")]
        assert!(result.is_err());
        #[cfg(not(feature = "cuda"))]
        assert!(result.is_ok()); // Stub accepts anything for world_size=1
    }

    #[test]
    fn test_multi_rank_requires_cuda() {
        let id = NcclComm::get_unique_id().unwrap();
        #[cfg(not(feature = "cuda"))]
        {
            let result = NcclComm::init(&id, 2, 0);
            assert!(result.is_err());
            let err_msg = format!("{}", result.unwrap_err());
            assert!(err_msg.contains("cuda"));
        }
    }
}
